# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Set env variables
        run: echo 'ENCRYPTION_KEY=f0PxnhtFrSnx3Sa2' >> .env && echo 'CLOUDINARY_API_SECRET=3xawB1jRtzsDYcVeSQGMY9161oA' >> .env && echo 'CLOUDINARY_API_KEY=492481131764584' >> .env && echo 'CLOUDINARY_NAME=workload-ng' >> .env && echo 'APP_NAME=FeedbackMonkey' >> .env && echo 'PORT=8080' >> .env && echo 'HOST=127.0.0.1' >> .env && echo 'HASH_DRIVER=bcrypt' >> .env && echo 'IPSTACK_KEY=fb89d273677a17cbbe28b521cc819737' >> .env && echo 'BUGSNAG_API_KEY=e1687cabad6b657b00a8e7f5741c9837' >> .env && echo 'APP_KEY=TUL5QiYJQypf0mY1S05KXEfyOh70Zh05' >> .env && echo 'NODE_ENV=testing' >> .env && echo 'DB_CONNECTION=sqlite' >> .env && echo 'DB_DATABSE=adonis' >> .env
      - name: Migrate DB
        run: node ace migration:run
      - name: Seed DB
        run: node ace seed
      - name: Execute test
        run: node ace test
      - name: Deploy
        run: curl https://api.feedmonkey.io/deploy?token=XP0aw2Dkrk22p0JoAOzulOl8XkUxlvkO

